### ISSUE TITLE
Contact Us Section

### ISSUE THREAD

**Issue by fantasticbuddy** [Souvik2376/Hacktober-Fest-2023-MyPetSpotlight#18]
Hey @Souvik2376 
I went through the repo and realized that there is no contact page in here. I think it is an important part of every webpage. I have enough of experience in making contact section. I would like to add one here.

Kindly assign me this issue under hacktober23
Thankyou.

**Comment by Souvik2376** [comment]
Ok . Please add this changes .

**Comment by Abhishek-465** [comment]
Please give the necessary contact details so that it can be added on the contact section.

**Comment by Souvik2376** [comment]
@Abhishek-465 Right now don't provide any details just leave it blank
