### ISSUE TITLE
#1 Make the navbar good and colorfull

### ISSUE THREAD

**Issue by Souvik2376** [Souvik2376/Hacktober-Fest-2023-MyPetSpotlight#20]
<img width="959" alt="image" src="https://github.com/Souvik2376/Hacktober-Fest-2023-MyPetSpotlight/assets/100219950/a8048116-d651-43d2-87e7-1f8f970b0da9">

Right now the navbar is not that kind of attractive anyone want to make it more prominent .

If anyone is interested please comment down and it will be assigned to you .

**Comment by Shanb98** [comment]
I'd like to modify the header and footer and make it responsive. If you want me to work on this please assign me under Hacktoberfest topic.

**Comment by Ash024** [comment]
hey there, I would love to contribute to your repository. Please assign me this issue.

**Comment by Souvik2376** [comment]
@Shanb98 is already working on this issue . U can contribute here by adding your pet here .Make direct PR if u want to add your pet card in this repo.

**Comment by Shanb98** [comment]
@Souvik2376  I completed the task you assigned. I'd love hear your feedback

**Comment by Souvik2376** [comment]
@Shanb98 Make the Welcome to my pet spotlight towards right instead of center and other thing in a dropdown menu
