### ISSUE TITLE
Add a more responsive header and a footer

### ISSUE THREAD

**Issue by Shanb98** [Souvik2376/Hacktober-Fest-2023-MyPetSpotlight#21]
I went through the repo and realized that there is some issues with header and the footer. I'd like to modify the header and footer and make it responsive. If you want me to work on this please assign me under Hacktoberfest topic.

**Comment by Souvik2376** [comment]
@Shanb98 there is already a issue based on which you want to work #20 . Please comment there and u will be assigned 😊.
