### ISSUE TITLE
To make "Add your pet" responsive

### ISSUE THREAD

**Issue by Anjali286** [Souvik2376/Hacktober-Fest-2023-MyPetSpotlight#30]
Hey @Souvik2376   
We can add a form for the "Add your pet" section. When the user submits the form, it captures the values entered in the form fields and displays them on the page.
Kindly assign this issue to me under Hacktoberfest 2k23

**Comment by Souvik2376** [comment]
U can update that but not right now || You can contribute here by adding your pet details ||
